config/routes.rb
Rails.application.routes.draw do

  root :to => 'application#index'

  get '/signout', :to => 'sessions#destroy', :as => 'signout'
  get '/sessions', :to => 'sessions#index', :as => 'login', :path => '/login'

  get '/about', :to => 'application#about', :as => 'about'
  get '/contact', :to => 'application#contact', :as => 'contact'
  get '/motherbase', :to => 'application#motherbase', :as => 'motherbase'

  resources :posts
  resources :categories
  resources :sessions
  resources :messages

  # Post paths
  get '/:category/:permalink', :to => 'posts#permalink_show', :as => 'permalink_post'

  # Category paths
  get '/category/:permalink', :to => 'category#category_show', :as => 'permalink_category'
  # get '/category/', :to => 'category#index', :as => 'categoria_home'

  resources :users do
    collection do
      
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base


end

app/models/message.rb
class Message < ActiveRecord::Base


end

app/models/post.rb
class Post < ActiveRecord::Base

belongs_to :user


end

app/models/session.rb
class Session < ActiveRecord::Base
  def self.sweep(time = 1.hour)
    if time.is_a?(String)
      time = time.split.inject { |count, unit| count.to_i.send(unit) }
    end
 
    delete_all "updated_at < '#{time.ago.to_s(:db)}'"
  end


end

app/models/user.rb
class User < ActiveRecord::Base

  before_create :assign_rank
  has_many :posts

  # Método para asignar permisos
  # 0: Default
  # 1: Admin
  def assign_rank(options={})
    if options.blank?
      self.rank = 0
    end
  end

  def admin?
    self.rank == 0
  end

  # Genera un Token de base 64
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Cifra usando SHA2 el token
  def User.encrypt(token)
    Digest::SHA2.hexdigest(token.to_s)
  end

  # Recibe una contraseña y comprueba si es esa contraseña
  def check_password(password_to_check)
    return (self.password == User.encrypt("--#{password_to_check}--#{self.created_at}--#{self.password_salt}"))
  end

  # Genera un Token único por sesión al usuario
  def generate_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end

  # Creacion de contraseña: Genera una contraseña para el usuario
  #   - Prepara una salt para el usuario
  #   - Encriptación de contraseña (contraseña, created_at, salt)
  def generate_password
    self.password_salt = User.encrypt("--#{Time.now.utc}--#{ENV['SALT']}")
    self.password = User.encrypt("--#{self.password}--#{self.created_at}--#{self.password_salt}")
    self.save
  end

  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
  
  def index
    # Manera para identificar la página principal del sitio web. Lo uso para SEO.
    @principal_page = true
    select_nav

    @posts = Post.page(params[:page].to_i).per(10)

  end

 def contact
    select_nav
  end

 def about
    select_nav
  end

  # GET /motherbase
  # Panel de control
  def motherbase
    if signed_in? and current_user.admin?
    
      respond_to do |format|
        format.html { render }
        format.js { render}
      end

    else
      redirect_to login_path
    end
  end


  def select_nav
    @active_nav = case params[:action]
      when 'about' then 'about'
      when 'contact' then 'contact'
    else nil
    end

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all.group_by{ |t| [t.created_at.year, t.created_at.month]}
    @active_nav = 'post_index'
  end

  def show
    if !(@post = Post.find_by(id: params[:id])).blank?
      render
      # Redirect permalink_show
    else
      # render_404
    end  
  end

  def permalink_show
    if !params[:permalink].blank? && !(@post = Post.find_by(permalink: params[:permalink])).blank?
      # Lógica con Permalink
    else
      # render_404
    end
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new

  end

  def index
    if signed_in?
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js {  }
      end     
    else

      @session = Session.new;

      respond_to do |format|
        format.html { render }
        format.js {  }
      end    
    end
  end
  
  # Crea la sesion
  def create
    # Busca al usuario por nombre o nick

    if (user = User.find_by(nick: params[:nick].downcase))

      # Comprueba la contraseña para ese usuario
      check_pass = user.check_password(params[:pass])


      if user.blank? or !check_pass
        respond_to do |format|
          format.html { redirect_to login_path }
          format.js {  }
        end
      else
        
        iniciar_sesion(user)
        self.current_user= user;

        respond_to do |format|
          format.html { redirect_to root_path }
          format.js {  }
        end
      end
    
    else
      redirect_to login_path
    end
  end

  # Elimina la sesión
  def destroy
    if signed_in?
      sign_out
    end

    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper

  # Date: [yyyy, mm]
  def show_date date
    Date.new(date[0], date[1]).to_datetime.strftime("%B %Y")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Crea la cookie para mantener la sesión y un Token para localizarla y validarla
  def iniciar_sesion(user)
    remember_token = User.new_remember_token
    
    cookies.permanent["PQ_remember_token"] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete("PQ_remember_token")
  end

  def signed_in?
    !current_user.blank?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies["PQ_remember_token"])
    @current_user ||= User.find_by_remember_token(remember_token)
  end

  # Comprueba si el usuario es el mismo que el usuario que navega
  def its_me?(user)
    return (signed_in? and (current_user.id == user.id))
  end

end

app/views/application/_column_box.html.haml
.secundary_box
  .box
    = render :partial => 'application/phrase_box'
  .box
    = render :partial => 'posts/post_box' #Falta
  .box
    = render :partial => 'application/ad_box' #Falta
  - if false #ocultos para evitar carga
    .box
      = render :partial => 'application/tweets_box'
    .box
      = render :partial => 'application/translate_box'
  .box
    = render :partial => 'categories/category_box' #Falta

app/views/application/_footer.html.haml
%footer.footer.text-center
  -#="Developed by Sergio Canis"

app/views/application/_header.html.haml
%header.header
  - if @principal_page
    %h1.title-site
      = link_to(root_path) do
        ="Prueba y Error"
      %small.sub-title="Inténtalo. Equivócate. Vuelve a intentarlo."

  - else
    .title-site
      = link_to(root_path) do
        ="Prueba y Error"
      %small.sub-title="Inténtalo. Equivócate. Vuelve a intentarlo."

  -#.collapse.navbar-collapse.navbar-ex1-collapse
  %ul.nav.nav-tabs.nav-justified
    %li{:role => "presentation", :class => (@active_nav.blank?) ? 'active' : nil}
      = link_to("Inicio", root_path)

    %li{:role => "presentation", :class => (!@active_nav.blank? and (@active_nav == 'post_index')) ? 'active' : nil}
      = link_to("Archivo", posts_path)

    %li{:role => "presentation", :class => (!@active_nav.blank? and (@active_nav == 'about')) ? 'active' : nil}
      = link_to("Acerca de", about_path)

    %li{:role => "presentation", :class => (!@active_nav.blank? and (@active_nav == 'contact')) ? 'active' : nil}
      = link_to("Contacto", contact_path)



-# h1 el Titulo del blog solo aquí. En posts#index debe ir en h1 el título de los posts

app/views/application/_phrase_box.html.haml
%h4="S. Sanchez Prieto"

%h5="A todos aquellos que luchan por lograr lo que buscan, porque la auténtica felicidad está en el camino y no en la meta"

app/views/application/_translate_box.html.haml
%h4="Traductor"

%h5="If you do not know Spanish, you can translate the content"
.text-right
  #MicrosoftTranslatorWidget.Dark{:style => "color:white;background-color:#555555"}
    :javascript
      setTimeout(function(){{var s=document.createElement('script');s.type='text/javascript';s.charset='UTF-8';s.src=((location && location.href && location.href.indexOf('https') == 0)?'https://ssl.microsofttranslator.com':'http://www.microsofttranslator.com')+'/ajax/v3/WidgetV3.ashx?siteData=ueOIGRSKkd965FeEGM5JtQ**&ctf=True&ui=true&settings=Manual&from=es';var p=document.getElementsByTagName('head')[0]||document.documentElement;p.insertBefore(s,p.firstChild); }},0);

app/views/application/_tweets_box.html.haml
.text-center
  %a.twitter-timeline{"data-widget-id" => "580054659475357697", :href => "https://twitter.com/SergioCC14"} Tweets by @SergioCC14
  :javascript
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

app/views/application/contact.html.haml
%h1="Contacto"

%div
  %p="Este es un blog de divulgación personal, pensado para que el autor aprenda y en el trayecto cuente sus experiencias. Por lo tanto todo lo que aquí se expresa es la humilde opinión del autor."

  %p="Si deseas ponerte en contacto conmigo puedes utilizar el formulario que aparece en la parte inferior. Toda critica constructiva sera bien recibida."


= form_for(Message.new, :html => {:class => 'contact_form'}) do |f|
  .form-inline
    .form-group
      = f.text_field :author, :class => 'form-control', :placeholder => 'Nombre'
    .form-group
      = f.text_field :email, :class => 'form-control', :placeholder => 'Email'
    
  .form-group
    = f.text_area :content, :class => 'form-control', :placeholder => 'Escriba aquí el motivo del contacto...'

  .form-group.pull-right
    = f.submit "Enviar", :class => 'btn btn-primary'

app/views/application/index.html.haml
%div{:style => 'padding: 20px 0'}
  - @posts.find_each do |p|
    = render :partial => 'posts/partial_show', :locals => {:post => p}

app/views/categories/_category_box.html.haml
%h4="Categorias"

app/views/layouts/application.html.haml
%html{:itemscope => "itemscope", :itemtype => "http://schema.org/WebPage"}
  %head
    %title Prueba y Error
    = stylesheet_link_tag    'application', media: "all", "data-turbolinks-track" => true
    = javascript_include_tag 'application', "data-turbolinks-track" => true
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

    = csrf_meta_tags
  %body
    #main_container.container
      .row
        = render :partial => 'application/header'
        
        #main_column
          .col-xs-12.col-sm-8.col-md-9.col-lg-9{:style => 'border-right: 1px solid #DDDDDD;'}
            = yield

        #secundary_column
          .col-xs-0.col-sm-4.col-md-3.col-lg-3
            = render :partial => 'application/column_box'


        .clearfix
        = render :partial => 'application/footer'

app/views/posts/_partial_show.html.haml
.post.preview
  .title-post=post.title
  .subtitle-post="Creado por #{post.user.nick} en #{post.created_at}"
  .content-post=raw(post.content.truncate(800)) if !post.content.blank?
  %div{:style => 'margin-bottom:10px;'}
  - if !post.content.blank? && post.content.length > 800
    = link_to " >> Seguir leyendo", post
    %hr

app/views/posts/_post_box.html.haml
%h4="Cuaderno de bitácora"

app/views/posts/index.html.haml
%dl
  - @posts.each do |date, post|
    %dt="#{show_date date}"
    - post.each do |p|
      %dd= p.title

app/views/posts/show.html.haml
%div{:style => 'padding: 20px 0'}
  .post
    %h1.title-post=@post.title
    %h2.subtitle-post="Creado por #{@post.user.nick} en #{@post.created_at}"
    .content-post=raw @post.content